- lib/constants/colors.dart
Created colors static resources
> created colors.dart

- lib/main.dart
- lib/ui/room.dart
Created room screen layout ptototype and changed app background color
> Layout prototype

- lib/main.dart
updated surface to match background color so appBar color will match background color
updated primary color, now all buttons are yellow by default
> updated colorScheme

- lib/ui/room.dart
Added loading progress bar,
Added appbar to layout
updated all dimensions using appbar height as reference to be replicable
> Updated layout

- lib/controller/game_controller.dart
- lib/router/parser.dart
- lib/ui/lobby.dart
- lib/ui/onboarding.dart
- lib/ui/set_user_name.dart
- lib/ui/settings.dart
- lib/ui/splash.dart
- lib/widgets/chat_balloon.dart
- Adds the onboarding pages
- Saves locally the language and username
- Adds a setting page to clear local data
- Skips language selection and onboarding if they were saved previously
> Add onboarding screen, set user name and settings

- lib/ui/vote_answer.dart
> created vote_answer Layout

- lib/constants/locale_string.dart
- lib/constants/styles.dart
- lib/ui/room.dart
- lib/ui/vote_answer.dart
- lib/widgets/app_button.dart
- lib/widgets/gray_stripe.dart
moved constant styles to styles
created reusable widget GrayStrype
created reusable widget AppButton
moved strings to LocaleStrings
> Room refactor

- lib/constants/colors.dart
- lib/main.dart
- lib/ui/correct_news.dart
- lib/ui/game_winner.dart
- lib/ui/lobby.dart
- lib/ui/room.dart
- lib/ui/round_winner.dart
- lib/ui/set_user_name.dart
- lib/ui/settings.dart
- lib/ui/show_news.dart
- lib/ui/vote_answer.dart
- lib/ui/vote_persona.dart
- lib/widgets/app_button.dart
- lib/widgets/chat_balloon.dart
- lib/widgets/gray_stripe.dart
Upated colors names, it will be easier to change gray pallete if needed
Button color is used in many locations, for better reading changed name to it's color
updated colors calls
> Colors refactor

- lib/ui/desc_persona.dart
> created desc_persona layout

- android/app/build.gradle
- android/app/src/debug/AndroidManifest.xml
- android/app/src/main/AndroidManifest.xml
- android/app/src/main/kotlin/com/never_heard/have_you_heard/MainActivity.kt
- android/app/src/profile/AndroidManifest.xml
- ios/Runner.xcodeproj/project.pbxproj
- linux/CMakeLists.txt
- Set unique applicationId
- The 'GradleException' issue started when I renamed the application ID, it seems gradle got stuck in a weird state and cannot recover, even after cleaning the caches and doing all sorts of what-nots.
> Change applicationId

- lib/ui/game_winner.dart
- lib/ui/lobby.dart
- lib/ui/room.dart
- lib/ui/show_news.dart
- lib/ui/vote_persona.dart
- lib/widgets/app_button.dart
- lib/widgets/icon_app_button.dart
refactored Lobby after PR #40 
Created IconAppButton, an AppButton with a leading Icon
Updated background Image to not move when keybord is activated
Updated to use custom widgets
Updated Dividers colors
> Lobby refactor

- lib/ui/set_user_name.dart
- lib/widgets/app_text_field.dart
Created widget AppTextField
AppTextField has filled background, now background image wont disturb the text reading
Fixed textField border color and radius
updated to use custom widgets GrayStrype and AppButton
> Set user name refactor

- lib/models/socket.dart
The 'room' event can come in at any moment, but only transition to Room screen if current screen is the Lobby.
> Don't always go to Room with room event

- lib/models/player.dart
- lib/ui/room.dart
The bar fills up when a player joins, and reverts when the player leaves.
> Animate player button

- lib/controller/game_controller.dart
- lib/controller/setting_controller.dart
- lib/models/socket.dart
- lib/ui/set_user_name.dart
- lib/ui/settings.dart
- lib/ui/splash.dart
- Sets the App language during onboarding
- Alllows the SettingScreen to change language at anytime
- The server is always up to date regarding player language preferences
> Set the App language

- lib/ui/set_user_name.dart
image had same issue as lobby
fixed floating background image by change it's size
> fix image size

- lib/main.dart
- lib/ui/settings.dart
- lib/widgets/app_text_field.dart
updated theme  colors:
background color (update progressBar backgroud colors) 
onPrimary color (set default color for button text ) 
onSurface color (set default appBar text color )
updated cursor color on AppTextfield and settings name
> Fix colors

- lib/ui/show_news.dart
updated TextField to an AppTextField with 25 character max input length
> updated TextField to AppTextField

- lib/constants/styles.dart
added a new class with app textstyles, it makes easyier to pick find style
> Add Hyh textstyles

- lib/ui/lobby.dart
Added a limit of 5 digits to room code TextField
> added length limiting on input

- lib/models/game.dart
- lib/models/news.dart
- lib/models/socket.dart
Display of the news were also updated
> Consume the new News format from the server

- lib/ui/onboarding.dart
Used pr #73 to lessen TextStyle uses
Removed circle page indicator from third page
updated Button on third page to an AppButton
Added a new forth page to redirect to "set user name"
Added const where it was possible
Now, you can navigate to "set user name" swiping left on third page or by the Button
(set user name will need an exit game popup to avoid returning to an empty screen)
> Onboarding refactor

- lib/constants/locale_string.dart
- lib/constants/styles.dart
- lib/ui/settings.dart
- lib/widgets/close_game_dialog.dart
fixed name textfield: 
now it can hold larger names
it clears when in focus
it shows a snackbar when update name
added  close game dialog
close game button now opens a closeGame dialog
added a custom snackbar
> Add settings behaviour

- lib/controller/game_controller.dart
- lib/controller/setting_controller.dart
- lib/models/socket.dart
- lib/ui/set_user_name.dart
- lib/ui/settings.dart
- lib/ui/splash.dart
- Send the a previous user ID to server, so we are recognized as a re-connection, rather than a new connection.
- Further organizes the name and language setting functions.
> Reconnect as same user

- lib/ui/onboarding.dart
updated onboarding text sizes
updated logo sizing
> updated onboarding text sizes

- lib/constants/styles.dart
- lib/ui/splash.dart
updated splash screen to change widgets sizes
updatex textfield textStyles
> Fix splash tablet

- lib/constants/styles.dart
- lib/ui/desc_persona.dart
added a scale factor to texts and image
> Fix desc persona

- lib/main.dart
- lib/utilities/app_scroll_behavior.dart
> Fix onboarding swipe web

- lib/ui/vote_persona.dart
now persona name and image size has a scaleFactor
> updated image size and text size

- lib/controller/game_controller.dart
- lib/models/socket.dart
- lib/ui/game_winner.dart
- The client sends a 'rematch` when the player wants to play again
- Otherwise the client sends 'leave' when the player wants to leave the room
- Also adjusted the Winner banner animations and timings.
> Implement game rematch

- lib/constants/styles.dart
- lib/constants/values.dart
- lib/ui/onboarding.dart
- lib/utilities/LayoutUtility.dart
refactored onboarding to not overflow images in onboarding
> Onboarding multiplatform prototype
